### ISSUE TITLE
Too many connections

### ISSUE THREAD

**Issue by OlliSchu** [Design-Computation-RWTH/bcfServer#4]
The BCF server is creating too many connections. Connections must be reused and not recreated. Saving the connection by Project GUID?

**Comment by GeorgDangl** [comment]
Stupid question maybe, but what's a connection? Are there connections being kept open, e.g. for web sockets or something?

**Comment by OlliSchu** [comment]
Hey Georg, no that has something to do with the current MongoDB Setup. The BCF Server creates connections to the MongoDB and if you are using e.g. a free plan of Mongo Atlas you are limited to 500 connections.

**Comment by GeorgDangl** [comment]
Ah, I see😀 I don't know a lot about NodeJS server side or MongoDb, but often ORMs (or whatever they're called for document databases😀) do have some kind of connection pooling / connection management available, so maybe you can find something there.

**Comment by OlliSchu** [comment]
Thanks for the advice! 😄 I will have a look at it
